server:
  port: 80

spring:
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: guest
    password: guest

mq:
  normalExchangeName: exchange.direct.delay
  deadExchangeName: exchange.direct.dead
  normalQueueName: queue.direct.delay
  deadQueueName: queue.direct.dead
  normalRoutingKey: delay
  deadRoutingKey: dead