server:
  port: 80

spring:
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: guest
    password: guest


mq:
  exchangeName: exchange.header
  queueAName: queue.header.a
  queueBName: queue.header.b