spring:
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated

mq:
  exchangeName: exchange.direct.normal
  queueName: queue.direct.normal
  routingKey: normal