spring:
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: guest
    password: guest

mq:
  delay-exchange-name: exchange.direct.delay
  delay-queue-name: queue.direct.delay
  delay-routing-key: delay